### ISSUE TITLE
Can't catch an exception while solving reCaptcha v3

### ISSUE THREAD

**Issue by svintuss** [Xewdy444/Playwright-reCAPTCHA#57]
Hi! 

Could you please help me solve a `playwright._impl._api_types.Error: Protocol error` exception while using `AsyncSolver`?
The issue is that I can't seem to catch it with `try... except` clause and as a result can't handle it properly. I would like to restart the browser or reload page on an exception.

Is this a `Playwright-reCAPTCHA` issue or a more general `playwright` error?

```
Exception in callback AsyncIOEventEmitter._emit_run.<locals>.callback(<Task finishe...js:118:20\n')>) at /Users/user/.pyenv/versions/3.11.5/lib/python3.11/site-packages/pyee/
asyncio.py:65                                                                                                                                                                 
handle: <Handle AsyncIOEventEmitter._emit_run.<locals>.callback(<Task finishe...js:118:20\n')>) at /Users/user/.pyenv/versions/3.11.5/lib/python3.11/site-packages/pyee/asynci
o.py:65>                                                                                                                                                                      
Traceback (most recent call last):                                                                                                                                            
  File "/Users/user/.pyenv/versions/3.11.5/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/user/.pyenv/versions/3.11.5/lib/python3.11/site-packages/pyee/asyncio.py", line 71, in callback
    self.emit("error", exc)
  File "/Users/user/.pyenv/versions/3.11.5/lib/python3.11/site-packages/pyee/base.py", line 179, in emit
    self._emit_handle_potential_error(event, args[0] if args else None)
  File "/Users/user/.pyenv/versions/3.11.5/lib/python3.11/site-packages/pyee/base.py", line 139, in _emit_handle_potential_error
    raise error
  File "/Users/user/.pyenv/versions/3.11.5/lib/python3.11/site-packages/playwright_recaptcha/recaptchav3/async_solver.py", line 52, in _extract_token
    token_match = re.search('"rresp","(.*?)"', await response.text())
                                               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/.pyenv/versions/3.11.5/lib/python3.11/site-packages/playwright/async_api/_generated.py", line 603, in text
    return mapping.from_maybe_impl(await self._impl_obj.text())
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/.pyenv/versions/3.11.5/lib/python3.11/site-packages/playwright/_impl/_network.py", line 564, in text
    content = await self.body()
              ^^^^^^^^^^^^^^^^^
  File "/Users/user/.pyenv/versions/3.11.5/lib/python3.11/site-packages/playwright/_impl/_network.py", line 560, in body
    binary = await self._channel.send("body")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/.pyenv/versions/3.11.5/lib/python3.11/site-packages/playwright/_impl/_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/.pyenv/versions/3.11.5/lib/python3.11/site-packages/playwright/_impl/_connection.py", line 482, in wrap_api_call
    return await cb()
           ^^^^^^^^^^
  File "/Users/user/.pyenv/versions/3.11.5/lib/python3.11/site-packages/playwright/_impl/_connection.py", line 97, in inner_send
    result = next(iter(done)).result()
             ^^^^^^^^^^^^^^^^^^^^^^^^^
playwright._impl._api_types.Error: Protocol error (Network.getResponseBody): Request "7518340251688" is not found getBase64EncodedResponse@chrome://juggler/content/NetworkObs
erver.js:826:13
getResponseBody@chrome://juggler/content/NetworkObserver.js:92:34
Network.getResponseBody@chrome://juggler/content/protocol/PageHandler.js:261:30
dispatch@chrome://juggler/content/protocol/Dispatcher.js:132:39
_dispatch@chrome://juggler/content/protocol/Dispatcher.js:69:36
receiveMessage@chrome://juggler/content/components/Juggler.js:118:20
```

**Comment by Xewdy444** [comment]
Could you provide a code snippet for me to test with and then I'll get an update out soon.

**Comment by svintuss** [comment]
Hi. Here's a code that may help reproduce the error. The error itself doesn't happen often, so you might want to run multiple browser instances and several contexts within each browser. 
I've noticed that this particular `playwright._impl._api_types.Error` error happens when all the content was loaded successfully but `https://www.google.com/recaptcha/api2/reload?....` script can't be loaded due to timeout or some other error. This condition can be met when page content is routed from `.har` file and only the captcha script requests network content.

With Firefox it's 
`playwright._impl._api_types.Error: Protocol error (Network.getResponseBody): Request "7518340251688" is not found getBase64EncodedResponse@chrome://juggler/content/NetworkObs`
With WebKit error description is slightly different:
`playwright._impl._api_types.Error: Protocol error (Network.getResponseBody): Missing content of resource for given requestId [{"code":-32000,"message":"Missing content of resource for given requestId"}]`


```
#!/usr/bin/python3

import asyncio
import aiofiles

from playwright.async_api import async_playwright, TimeoutError as PlaywrightTimeoutError, Error as PlaywrightError
from playwright_recaptcha import recaptchav3
from playwright_recaptcha.errors import RecaptchaTimeoutError

async def pw():
    while True:
        async with async_playwright() as playwright:
            print('Started pw()')
            browser = await playwright.firefox.launch(headless=True)
            device = playwright.devices['Desktop Firefox']

            async with asyncio.TaskGroup() as tg:
                for _ in range(4):
                    task = tg.create_task(createCaptchaContext(browser, device))
                    print(f'Launched task')
                
            print('Captcha solver exited')

async def createCaptchaContext(browser, device):
    while True:
        try:      
            context = await browser.new_context(**device, ignore_https_errors=True) 
        except Exception as err:
            print(f'new_context() err: {err}')
        context.set_default_timeout(15000)
        print("NewContext created")
        try:
            await createCaptchaPage(context, proxy=proxy)
            await context.close()
            print("CaptchaSolver Cycle End")
        except PlaywrightTimeoutError as err:
            print(f'{err.name}: {err.message}')
            return
        except PlaywrightError as err:
            print(f'{err.name}: {err.message}')
            return
        except Exception as err:
            print(f'Proxy: {proxy}. Error: {err}')
            return

async def createCaptchaPage(context, proxy=''):
    page = await context.new_page()
    await page.route_from_har(f'HAR.har', update=False, update_content='embed',  not_found='block', update_mode='minimal')  # Create HAR beforehand
        
    try:
        async with recaptchav3.AsyncSolver(page) as solver:
            await page.goto("https://antcpt.com/score_detector/")
            for _ in range(2):
                try:
                    token = await solver.solve_recaptcha(timeout=10)
                    print(token)
                    break
                except RecaptchaTimeoutError:
                    print(f'Recaptcha Timeout Error: {proxy}')
                    await asyncio.sleep(5)
                    continue
    except Exception as err:
        print(f'AsyncSolver() exception: {err}') # Catches navigating to "https://antcpt.com/score_detector/", waiting until "load" error

    return

async def launchSolvers():
    await asyncio.gather(*[pw() for _ in range(4)])

if __name__ == '__main__':
    loop = asyncio.get_event_loop()
    loop.run_until_complete(launchSolvers())
```

**Comment by Xewdy444** [comment]
Well, to answer your initial question, this is an issue with Playwright itself not handling this situation properly. I believe any attempt at checking if the request is still found would result in a similar error. Therefore, I don't think there is really anything I can about this.
